version: '2.13'

services:
  app:
    build: .
    volumes:
      - .:/var/www/ci
    ports:
      - 9000:9000
    networks:
      - ci-network
  
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/ci
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - ci-network
      
  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: jcD12345678
    networks:
      - ci-network
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 7000:80
    networks:
      - ci-network

volumes:
  db-data:

networks:
  ci-network:
    driver: bridge